#!/bin/bash

url=$1

path=${url#https://app.codility.com/programmers/lessons/}
path=${path%%/}
echo "creating required files for $path"

if [[ -d $path ]]; then
    echo "$path already exists, creating missing files only"
    # exit 1
fi

mkdir -p $path

# if [[ ! -f $path/index.js ]]; then
#     touch $path/index.js
# fi

if [[ ! -f $path/index.test.js ]]; then
    echo "const { solution } = require('./index');

test('Basic test', () => {
    // expect(solution(true)).toBe(true);
})" >$path/index.test.js
fi

node fetch.js $url

echo "scaffolding done."
