#!/bin/bash

url=$1

path=${url#https://app.codility.com/programmers/lessons/}
path=${path%%/}
echo "creating required files for $path"

if [[ -d $path ]]; then
    echo "$path already exists aborting."
    exit 1
fi

mkdir -p $path

echo "function solution() {

}

module.exports.solution = solution;
" >$path/index.js

echo "const { solution } = require('./index');

test('Basic test', () => {
        expect(
            solution(true)
        ).toBe(true);
})
" >$path/index.test.js

echo "$url" >$path/readme.md

node fetch.js $url

echo "scaffolding done."
